permalink: /:categories/:title/
url: "http://bocetos.github.io"
full_name: "El Gato Escaldado"
first_name: "El Gato"
last_name: "Escaldado"
blog_title: "Av. Independencia 3548, Boedo, C.A.B.A – Tel: (54-11) 4932-1956 – elgatoescaldadolibros@gmail.com horario: martes a viernes de 10 a 13 hs. y de 16 a 20 hs., sábados de 10 a 14 hs. (lunes y domingos CERRADO)"
description: "Av. Independencia 3548, Boedo, C.A.B.A – Tel: (54-11) 4932-1956 – elgatoescaldadolibros@gmail.com horario: martes a viernes de 10 a 13 hs. y de 16 a 20 hs., sábados de 10 a 14 hs. (lunes y domingos CERRADO)"
author_img_name_path: "/images/users/user.jpg"
disqus_shortname: "example"
copyright_year: "2016"
google_analytics_code: ""
aboutme: "Av. Independencia 3548, Boedo, C.A.B.A – Tel: (54-11) 4932-1956 – elgatoescaldadolibros@gmail.com horario: martes a viernes de 10 a 13 hs. y de 16 a 20 hs., sábados de 10 a 14 hs. (lunes y domingos CERRADO)"
